name: Create release

on:
  schedule:
    - cron: '20 4 7 * *'
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and cache node dependencies
        uses: bahmutov/npm-install@v1

      - name: Build version
        id: build_version
        run: |
          INIT=$(date -d "1995-04-07" '+%s')
          NOW=$(date '+%s')
          DIFF=$((NOW - INIT))
          Y=$(($(date -d @$DIFF '+%-Y') - 1970))
          M=$(($(date -d @$DIFF '+%-m') - 1))
          VERSION="v0.$Y.$M"
          echo "$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update VERSION.md
        run: sed --debug -i "11 c \\Version $VERSION" VERSION.md
        env:
          VERSION: ${{ steps.build_version.outputs.version }}

      - name: Build changelog
        id: build_changelog
        run: |
          CHANGELOG=$(node scripts/changelog.mjs VictorWinberg $VERSION)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          VERSION: ${{ steps.build_version.outputs.version }}

      - name: Git commit
        run: |
          git config --global user.name 'VictorWinberg Actions'
          git config --global user.email 'victorwinberg-actions@users.noreply.github.com'
          git status
          git commit -am "🔖 $VERSION"
          git tag -a $VERSION -m "$VERSION"
          git push --follow-tags
        env:
          VERSION: ${{ steps.build_version.outputs.version }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.build_version.outputs.version }}
          body: ${{ steps.build_changelog.outputs.changelog }}
